FROM edimossilva/memory_app_rails

COPY ./backend_rails /app

RUN bundle install

RUN mkdir -p tmp/pids

CMD bundle exec puma -C config/puma.rb

# docker build -f Dockerfile.web -t edimossilva/memory_app_back .
# docker push edimossilva/memory_app_back
# docker build -f Dockerfile.web -t edimossilva/memory_app_back:v1 .
# docker push edimossilva/memory_app_back:v1
# docker run -p 3000:3000 --env-file .isolated_docker.env --network="host" edimossilva/memory_app_back
