# frozen_string_literal: true

namespace :coverage do
  desc 'Collates all result sets generated by the different test runners'
  task :report do
    require 'simplecov'
    puts Dir['cov/input/*.json']
    SimpleCov.collate Dir['cov/input/*.json']
  end
end
